services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    networks:
      - revio-network
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - revio-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - revio-network

volumes:
  postgres_data:
  redis_data:


networks:
  revio-network:
  external: true
