name: AWS prod API Environment

on:
  push:
    branches:
      - prod

jobs:
  setup:
    environment: prod
    runs-on:
      - self-hosted
      - prod

    steps:
      - name: Clean workspace
        run: |
          sudo rm -rf $GITHUB_WORKSPACE/* || true
          sudo rm -rf $GITHUB_WORKSPACE/.* || true

      - uses: actions/checkout@v3

      - name: Set correct permissions
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE

      - name: Generate .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_PORT: ${{ secrets.PORT }}
          envkey_NODE_ENV: ${{ secrets.NODE_ENV }}
          envkey_DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          envkey_DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

          envkey_REDIS_HOST: ${{ secrets.REDIS_HOST }}
          envkey_REDIS_PORT: ${{ secrets.REDIS_PORT }}
          envkey_REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          envkey_REDIS_URL: ${{ secrets.REDIS_URL }}



          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          envkey_JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}

          envkey_API_PREFIX: ${{ secrets.API_PREFIX }}


          envkey_LOG_LEVEL: ${{ secrets.LOG_LEVEL }}

          
   
          file_name: .env
          fail_on_empty: false
          
  build:
    environment: prod
    runs-on:
      - self-hosted
      - prod

    steps:
      - name: Set correct permissions
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE

      # Step to clean Docker cache
      - name: Clean Docker cache
        run: |
          docker system prune --all --volumes --force

      - name: Run unit tests
        # run: npm run test
        run: |
          docker compose run app npm test

      # Deploy with Docker Compose
      - name: Build with Docker Compose
        run: |
          # Stop and remove existing containers and networks
          docker compose build --force-rm --no-cache
          docker compose down --remove-orphans

      - name: Clean up after Docker
        if: always()
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE

  deploy:
    environment: prod
    runs-on:
      - self-hosted
      - prod

    needs:
      - build

    steps:
      - name: Set correct permissions
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE

      # Deploy with Docker Compose
      - name: Deploy with Docker Compose
        run: |
          # Start the application with Docker Compose
          docker compose up -d --force-recreate

      - name: Clean up after Docker
        if: always()
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE